version: 2.1
orbs:
  cypress: cypress-io/cypress@2.1.0

commands: # a reusable command with parameters
  with-rust-setup:
    parameters:
      do:
        default: []
        type: steps
    steps:
      - run:
          name: Set Cargo Parallel Jobs Setting
          command: echo 'export "CARGO_BUILD_JOBS"="8"' >> $BASH_ENV

      - run:
          name: Print Rust Versions
          command: rustc --version; cargo --version; rustup --version

      - run: apt update && apt install -y protobuf-compiler

      - steps: << parameters.do >>
jobs:
  lint-rust:
    docker:
      - image: rust:latest
    resource_class: medium
    steps:
      - checkout

      - with-rust-setup:
          do:
            - run:
                name: Install Rust Format
                command: rustup component add rustfmt

            - run:
                name: Test Formatting
                command: cargo fmt -- --check

            - run:
                name: Clippy
                command: rustup component add clippy && cargo clippy --workspace --no-deps
  doc-rust:
    docker:
      - image: rust:latest
    resource_class: small
    steps:
      - checkout

      - with-rust-setup:
          do:
            - run:
                name: Generate Docs
                command: cargo doc --workspace --no-deps
  test-rust:
    docker:
      - image: rust:latest
    resource_class: small
    steps:
      - checkout

      - with-rust-setup:
          do:
            - attach_workspace:
                at: target

            - run:
                name: Run Tests
                command: cargo test --locked 
  build-rust:
    docker:
      - image: rust:latest
    resource_class: xlarge
    environment:
      DATABASE_URL: "sqlite:./main.db"
      SQLX_OFFLINE: true
    steps:
      - checkout

      - with-rust-setup:
          do:
            - run:
                name: Build
                command: cargo build --locked --all-targets

      - store_artifacts:
          path: target/debug/peek
          destination: peek
      - persist_to_workspace:
          root: target
          paths:
            - debug/
            - sqlx/
            - CACHEDIR.TAG

  build-release-rust:
    docker:
      - image: rust:latest
    resource_class: xlarge
    environment:
      DATABASE_URL: "sqlite:./main.db"
      SQLX_OFFLINE: true
    steps:
      - checkout
      - with-rust-setup:
          do:
            - run:
                name: Build
                command: cargo build --release --locked --all-targets
      - store_artifacts:
          path: target/release/peek
          destination: peek
      - persist_to_workspace:
          root: target
          paths:
            - release/

  check-db-schema:
    docker:
      - image: rust:latest
    resource_class: xlarge
    environment:
      DATABASE_URL: "sqlite:/root/project/server/main.db"
      SQLX_OFFLINE: true
    steps:
      - checkout

      - with-rust-setup:
          do:
            - attach_workspace:
                at: target

            - restore_cache:
                keys:
                  - v1-sqlx-cli-{{ arch }}-0.6.2
            - run: cargo install sqlx-cli --version 0.6.2
            - save_cache:
                key: v1-sqlx-cli-{{ arch }}-0.6.2
                paths:
                  - /usr/local/cargo/bin/cargo-sqlx
                  - /usr/local/cargo/bin/sqlx

            - run:
                name: Setup DB
                command: cd server && cargo sqlx database setup

            - run:
                name: Check prepared sqlx schema
                command: cd server && cargo sqlx prepare --check
  deploy-fly:
    docker:
      - image: rust:latest
    resource_class: small
    steps:
      - checkout
      - attach_workspace:
          at: target
      - run: curl -L https://fly.io/install.sh | sh
      - run: echo 'export FLYCTL_INSTALL="/root/.fly"' >> $BASH_ENV
      - run: echo 'export PATH="$FLYCTL_INSTALL/bin:$PATH"' >> $BASH_ENV

      - run: flyctl deploy --app peek --local-only --dockerfile Dockerfile.circleci

workflows:
  version: 2
  ci:
    jobs:
      - build-rust
      - build-release-rust:
          filters:
            branches:
              only:
                - 'main'
      - check-db-schema:
          requires:
            - build-rust
      - lint-rust
      - doc-rust
      - test-rust:
          requires:
            - build-rust
      - cypress/run:
          requires:
            - build-rust
          working_directory: browser-tests
          executor: cypress/base-16-14-2-slim
          attach-workspace: false
          store_artifacts: true
          no-workspace: true
          cache-key: 'cache-{{ arch }}-{{ .Branch }}-{{ checksum "browser-tests/package.json" }}'
          yarn: true
          start: ../target/debug/peek
          post-checkout:
            - attach_workspace:
                at: target
      - deploy-fly:
          context:
            - Fly.io
          requires:
            - test-rust
            - doc-rust
            - check-db-schema
            - lint-rust
            - cypress/run
            - build-release-rust
          filters:
            branches:
              only:
                - 'main'


