version: 2.1
orbs:
  cypress: cypress-io/cypress@1

commands: # a reusable command with parameters
  with-rust-setup:
    parameters:
      do:
        default: []
        type: steps
    steps:
      - run:
          name: Set Cargo Parallel Jobs Setting
          command: echo 'export "CARGO_BUILD_JOBS"="8"' >> $BASH_ENV

      - run:
          name: Print Rust Versions
          command: rustc --version; cargo --version; rustup --version

      - steps: << parameters.do >>
jobs:
  lint-rust:
    docker:
      - image: rust:latest
    resource_class: medium
    steps:
      - checkout

      - with-rust-setup:
          do:
            - run:
                name: Install Rust Format
                command: rustup component add rustfmt

            - run:
                name: Test Formatting
                command: cargo fmt -- --check

            - run:
                name: Clippy
                command: rustup component add clippy && cargo clippy --workspace --no-deps
  build-and-test-rust:
    docker:
      - image: rust:latest
    resource_class: xlarge
    steps:
      - checkout

      - with-rust-setup:
          do:
            - run:
                name: Build
                command: cargo build --locked --all-targets

            - run:
                name: Run Tests
                command: cargo test --locked

            - run:
                name: Build Docs
                command: cargo doc --workspace --no-deps

      - store_artifacts:
          path: target/debug/yanwa
          destination: yanwa
      - persist_to_workspace:
          root: target
          paths:
            - debug/yanwa
  deploy-fly:
    docker:
      - image: rust:latest
    resource_class: small
    steps:
      - checkout

      - run: curl -L https://fly.io/install.sh | sh
      - run: echo 'export FLYCTL_INSTALL="/root/.fly"' >> $BASH_ENV
      - run: echo 'export PATH="$FLYCTL_INSTALL/bin:$PATH"' >> $BASH_ENV

      - run: flyctl deploy --app yanwa --remote-only

workflows:
  version: 2
  ci:
    jobs:
      - build-and-test-rust
      - lint-rust
      - cypress/run:
          requires:
            - build-and-test-rust
          working_directory: browser-tests
          executor: base-16-14-2-slim
          attach-workspace: false
          store_artifacts: true
          no-workspace: true
          cache-key: 'cache-{{ arch }}-{{ .Branch }}-{{ checksum "browser-tests/package.json" }}'
          yarn: true
          start: ../target/debug/yanwa
          post-checkout:
            - attach_workspace:
                at: target

      - deploy-fly:
          context:
            - Fly.io
          requires:
            - build-and-test-rust
            - lint-rust
            - cypress/run
          filters:
            branches:
              only:
                - 'main'


