// generated by `sqlx migrate build-script`
// and augmented by us to add the frontend pkb recompile
fn main() {
    // trigger recompilation when a new migration is added
    println!("cargo:rerun-if-changed=migrations");
    println!("cargo:rerun-if-changed=../frontend/pkg");
}
